image:
  name: "app-checker"
  tag: "2.0.0"
Installation:
  V1:
    Name: mylocal
    Registry:
      Domain: quay.io
    Secret:
      Draughtsman:
        SecretYaml: |+
          service:
            deployer:
              eventer:
                github:
                  oauthtoken: 51884676b1418b9b16f96d580f65b5e6d441a79b
pod:
  user:
    id: 1000
  group:
    id: 1000
project:
  branch: "master"
  commit: "1.1.1"
