# Default values for app-checker-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

port: 8000

image:
  repository: giantswarm/app-checker
  tag: [[ .Version ]]

Installation:
  V1:
    Kubernetes:
      API:
        Address: ""
    Name: mylocal
    Registry:
      Domain: quay.io
    Secret:
      AppChecker:
        GithubOAuthToken: ""

userID: 1000
groupID: 1000

replicas: 1

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

deployment:
  requests:
    cpu: 250m
    memory: 250Mi
