apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "resource.default.name"  . }}
  namespace: {{ include "resource.default.namespace"  . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
data:
  config.yml: |
    server:
      enable:
        debug:
          server: true
      listen:
        address: 'http://0.0.0.0:8000'
    service:
      appchecker:
        environment: '{{ .Values.Installation.V1.Name }}'
        {{- $v := .Values.Installation.V1.Secret.Draughtsman.SecretYaml  | fromYaml }}
        gitHubOAuthToken: '{{ $v.service.deployer.eventer.github.oauthtoken }}'
      kubernetes:
        address: ''
        inCluster: true
        tls:
          caFile: ''
          crtFile: ''
          keyFile: ''
